/* Auto-generated by tools/build-data.py — edit the copy there, then re-run, not here.
   16 sections, 53 placements, 52 unique Vimeo uploads.
*/

export interface Work {
  id: string;
  title: string;
  slug: string;
  aspect: string;
  duration: number;
  w: number;
  h: number;
  tone: string;
  discipline: string;
  kicker: string;
}

export interface Section {
  slug: string;
  title: string;
  kicker: string;
  blurb: string;
  accent: string;
  works: Work[];
}

export interface Skill {
  name: string;
  desc: string;
}

export interface Service {
  name: string;
  desc: string;
}

export interface PortfolioStats {
  edits: number;
  categories: number;
}

export const SECTIONS: Section[] = [
  {
    "slug": "absolute-cinema",
    "title": "Absolute Cinema",
    "kicker": "Craft",
    "blurb": "Pure colour and composition. Film-grade looks built from scratch — highlight roll-off, split-toned shadows, restrained contrast — on footage that has to carry a mood before a single word is spoken.",
    "accent": "#CCBA8E",
    "works": [
      {
        "id": "1220554546",
        "title": "Mumbai",
        "slug": "mumbai",
        "aspect": "16:9",
        "duration": 30,
        "w": 1280,
        "h": 720,
        "tone": "#66584c",
        "discipline": "absolute-cinema",
        "kicker": "Craft"
      },
      {
        "id": "1220555808",
        "title": "Jackie Chan — Cinematic",
        "slug": "jackie-chan-cinematic",
        "aspect": "4:3",
        "duration": 16,
        "w": 1280,
        "h": 960,
        "tone": "#22281b",
        "discipline": "absolute-cinema",
        "kicker": "Craft"
      },
      {
        "id": "1220555284",
        "title": "She's Running Out the Door",
        "slug": "shes-running-out-the-door",
        "aspect": "16:9",
        "duration": 37,
        "w": 1280,
        "h": 725,
        "tone": "#6f6050",
        "discipline": "absolute-cinema",
        "kicker": "Craft"
      },
      {
        "id": "1220556151",
        "title": "Conroy — Cinematic Reel",
        "slug": "conroy-cinematic-reel",
        "aspect": "16:9",
        "duration": 22,
        "w": 1280,
        "h": 720,
        "tone": "#564b41",
        "discipline": "absolute-cinema",
        "kicker": "Craft"
      }
    ]
  },
  {
    "slug": "concert-edits",
    "title": "Concert Edits",
    "kicker": "Client work",
    "blurb": "Ankit Tiwari live at Nirma. Stage lighting is the hardest grade there is — blown highlights, coloured wash, no second take. Cut to the performance, graded to keep skin tones intact under moving colour.",
    "accent": "#E0407A",
    "works": [
      {
        "id": "1219763361",
        "title": "Ankit Tiwari — Live at Nirma",
        "slug": "ankit-tiwari-live-at-nirma",
        "aspect": "16:9",
        "duration": 42,
        "w": 1280,
        "h": 720,
        "tone": "#1d110d",
        "discipline": "concert-edits",
        "kicker": "Client work"
      }
    ]
  },
  {
    "slug": "masking",
    "title": "Masking & Compositing",
    "kicker": "Craft",
    "blurb": "Frame-by-frame masking and compositing: subjects lifted from their plates, type threaded behind moving bodies, elements placed inside the scene so the graphic reads as part of the shot.",
    "accent": "#F27DB5",
    "works": [
      {
        "id": "1219757810",
        "title": "LJ — Masked Edit",
        "slug": "lj-masked-edit",
        "aspect": "4:3",
        "duration": 20,
        "w": 1280,
        "h": 960,
        "tone": "#23201b",
        "discipline": "masking",
        "kicker": "Craft"
      }
    ]
  },
  {
    "slug": "motion-graphics",
    "title": "Motion Graphics",
    "kicker": "Craft",
    "blurb": "After Effects motion work: velocity-driven type, kinetic layout and title systems that move with the cut rather than sitting on top of it. Horizontal and vertical builds.",
    "accent": "#66FFDE",
    "works": [
      {
        "id": "1219763331",
        "title": "Stranger Things",
        "slug": "stranger-things",
        "aspect": "16:9",
        "duration": 47,
        "w": 1280,
        "h": 720,
        "tone": "#b11a09",
        "discipline": "motion-graphics",
        "kicker": "Craft"
      },
      {
        "id": "1219763230",
        "title": "LJ — Velocity / Poster Boy",
        "slug": "lj-velocity-poster-boy",
        "aspect": "16:9",
        "duration": 18,
        "w": 1280,
        "h": 720,
        "tone": "#9f8874",
        "discipline": "motion-graphics",
        "kicker": "Craft"
      },
      {
        "id": "1219758725",
        "title": "House of Hobos",
        "slug": "house-of-hobos",
        "aspect": "9:16",
        "duration": 12,
        "w": 1280,
        "h": 2276,
        "tone": "#24170a",
        "discipline": "motion-graphics",
        "kicker": "Craft"
      }
    ]
  },
  {
    "slug": "fast-montage",
    "title": "Fast-Paced Montage",
    "kicker": "Rhythm",
    "blurb": "Seven montages cut to the beat. Frame-accurate sync, speed-ramped transitions and a build that keeps escalating — the format that holds a scrolling viewer past the three-second mark.",
    "accent": "#FE3448",
    "works": [
      {
        "id": "1220413186",
        "title": "Rock Your Body",
        "slug": "rock-your-body",
        "aspect": "16:9",
        "duration": 24,
        "w": 1280,
        "h": 720,
        "tone": "#b76f62",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220553507",
        "title": "Ruthless — LJ",
        "slug": "ruthless-lj",
        "aspect": "16:9",
        "duration": 18,
        "w": 1280,
        "h": 720,
        "tone": "#54392e",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220548695",
        "title": "Riverfront Montage",
        "slug": "riverfront-montage",
        "aspect": "16:9",
        "duration": 14,
        "w": 1280,
        "h": 721,
        "tone": "#72100b",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220554808",
        "title": "Ahmedabad BRTS",
        "slug": "ahmedabad-brts",
        "aspect": "16:9",
        "duration": 24,
        "w": 1280,
        "h": 720,
        "tone": "#fc5519",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220559375",
        "title": "Abhivyakti",
        "slug": "abhivyakti",
        "aspect": "16:9",
        "duration": 20,
        "w": 1280,
        "h": 720,
        "tone": "#453117",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220557252",
        "title": "Radiohead",
        "slug": "radiohead",
        "aspect": "16:9",
        "duration": 36,
        "w": 1280,
        "h": 719,
        "tone": "#892737",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      },
      {
        "id": "1220559007",
        "title": "Auditorium Jamming",
        "slug": "auditorium-jamming",
        "aspect": "16:9",
        "duration": 81,
        "w": 1280,
        "h": 720,
        "tone": "#210808",
        "discipline": "fast-montage",
        "kicker": "Rhythm"
      }
    ]
  },
  {
    "slug": "brand-films",
    "title": "Brand Films",
    "kicker": "Client work",
    "blurb": "A full campaign for Conroy — one cinematic hero film cut for the brand's landing page, then nine vertical reels carved out of the same shoot for Instagram and YouTube Shorts. One grade, one rhythm, ten deliverables.",
    "accent": "#E8B04B",
    "works": [
      {
        "id": "1220556151",
        "title": "Conroy — Cinematic Reel",
        "slug": "conroy-cinematic-reel",
        "aspect": "16:9",
        "duration": 22,
        "w": 1280,
        "h": 720,
        "tone": "#564b41",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220552857",
        "title": "Conroy — Reel 01",
        "slug": "conroy-reel-01",
        "aspect": "9:16",
        "duration": 22,
        "w": 1280,
        "h": 2276,
        "tone": "#6e5b55",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220550982",
        "title": "Conroy — Reel 02",
        "slug": "conroy-reel-02",
        "aspect": "9:16",
        "duration": 19,
        "w": 1280,
        "h": 2276,
        "tone": "#664f48",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220550831",
        "title": "Conroy — Reel 03",
        "slug": "conroy-reel-03",
        "aspect": "9:16",
        "duration": 17,
        "w": 1280,
        "h": 2276,
        "tone": "#dfd3d1",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220550347",
        "title": "Conroy — Reel 04",
        "slug": "conroy-reel-04",
        "aspect": "9:16",
        "duration": 34,
        "w": 1280,
        "h": 2276,
        "tone": "#d4caae",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220549555",
        "title": "Conroy — Reel 05",
        "slug": "conroy-reel-05",
        "aspect": "9:16",
        "duration": 24,
        "w": 1280,
        "h": 2276,
        "tone": "#8b6e66",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220549430",
        "title": "Conroy — Reel 06",
        "slug": "conroy-reel-06",
        "aspect": "9:16",
        "duration": 14,
        "w": 1280,
        "h": 2276,
        "tone": "#cac6c7",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220549151",
        "title": "Conroy — Reel 07",
        "slug": "conroy-reel-07",
        "aspect": "9:16",
        "duration": 19,
        "w": 1280,
        "h": 2276,
        "tone": "#73614b",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220548698",
        "title": "Conroy — Reel 08",
        "slug": "conroy-reel-08",
        "aspect": "9:16",
        "duration": 20,
        "w": 1280,
        "h": 2276,
        "tone": "#d0baac",
        "discipline": "brand-films",
        "kicker": "Client work"
      },
      {
        "id": "1220548696",
        "title": "Conroy — Reel 09",
        "slug": "conroy-reel-09",
        "aspect": "9:16",
        "duration": 12,
        "w": 1280,
        "h": 2276,
        "tone": "#3c4a4c",
        "discipline": "brand-films",
        "kicker": "Client work"
      }
    ]
  },
  {
    "slug": "event-edits",
    "title": "Event Edits",
    "kicker": "Client work",
    "blurb": "Live folk concerts, campus activations and hackathons. Multi-cam coverage cut to the energy of the room, delivered in both horizontal recap and vertical reel formats so the client can post everywhere from one shoot.",
    "accent": "#FF6F64",
    "works": [
      {
        "id": "1219767934",
        "title": "Halaji Tara Hath Vakhanu — Rushabh Ahir Live",
        "slug": "halaji-tara-hath-vakhanu-rushabh-ahir-live",
        "aspect": "16:9",
        "duration": 47,
        "w": 1280,
        "h": 720,
        "tone": "#1b1910",
        "discipline": "event-edits",
        "kicker": "Client work"
      },
      {
        "id": "1219766019",
        "title": "Nirma Activity Reel",
        "slug": "nirma-activity-reel",
        "aspect": "16:9",
        "duration": 32,
        "w": 1280,
        "h": 720,
        "tone": "#241c1d",
        "discipline": "event-edits",
        "kicker": "Client work"
      },
      {
        "id": "1219758002",
        "title": "Hackathon — The Full Film",
        "slug": "hackathon-the-full-film",
        "aspect": "16:9",
        "duration": 128,
        "w": 1280,
        "h": 720,
        "tone": "#5b7075",
        "discipline": "event-edits",
        "kicker": "Client work"
      },
      {
        "id": "1220556772",
        "title": "Rushabh Ahir — Vertical Cut",
        "slug": "rushabh-ahir-vertical-cut",
        "aspect": "9:16",
        "duration": 42,
        "w": 1280,
        "h": 2276,
        "tone": "#4b3a30",
        "discipline": "event-edits",
        "kicker": "Client work"
      },
      {
        "id": "1220556182",
        "title": "Pyaar Kya Hai",
        "slug": "pyaar-kya-hai",
        "aspect": "9:16",
        "duration": 38,
        "w": 1280,
        "h": 2276,
        "tone": "#c8866b",
        "discipline": "event-edits",
        "kicker": "Client work"
      },
      {
        "id": "1220556261",
        "title": "Tech Café",
        "slug": "tech-cafe",
        "aspect": "9:16",
        "duration": 24,
        "w": 1280,
        "h": 2276,
        "tone": "#938571",
        "discipline": "event-edits",
        "kicker": "Client work"
      }
    ]
  },
  {
    "slug": "event-gfx",
    "title": "Event GFX Animation",
    "kicker": "Craft",
    "blurb": "Broadcast-style graphics package for a hackathon — animated title sequence, lower thirds and stingers built to hold up on a projector and on a phone.",
    "accent": "#7AB9E0",
    "works": [
      {
        "id": "1219757999",
        "title": "Hackathon — Title Sequence",
        "slug": "hackathon-title-sequence",
        "aspect": "16:9",
        "duration": 7,
        "w": 1280,
        "h": 720,
        "tone": "#01003d",
        "discipline": "event-gfx",
        "kicker": "Craft"
      }
    ]
  },
  {
    "slug": "3d-visualization",
    "title": "3D Visualization",
    "kicker": "Craft",
    "blurb": "Product visualisation built in 3D — a card rendered, lit and animated for a vertical spot, then graded to match the rest of the brand's footage.",
    "accent": "#A78BFA",
    "works": [
      {
        "id": "1219760653",
        "title": "Card — 3D Visual",
        "slug": "card-3d-visual",
        "aspect": "9:16",
        "duration": 13,
        "w": 1280,
        "h": 2276,
        "tone": "#6e4e62",
        "discipline": "3d-visualization",
        "kicker": "Craft"
      }
    ]
  },
  {
    "slug": "smooth-movie",
    "title": "Smooth Movie Edits",
    "kicker": "Rhythm",
    "blurb": "The opposite discipline. Long, unhurried cuts that let a performance breathe, with transitions you feel rather than notice.",
    "accent": "#9BB8A8",
    "works": [
      {
        "id": "1220413187",
        "title": "Enola Holmes",
        "slug": "enola-holmes",
        "aspect": "4:3",
        "duration": 24,
        "w": 1280,
        "h": 961,
        "tone": "#1d1514",
        "discipline": "smooth-movie",
        "kicker": "Rhythm"
      }
    ]
  },
  {
    "slug": "podcast",
    "title": "Podcast Edits",
    "kicker": "Long form",
    "blurb": "Multi-cam podcast editing — clean speaker cuts, dead-air tightening, dialogue levelling and a consistent grade across cameras that never quite match.",
    "accent": "#F0A868",
    "works": [
      {
        "id": "1219766024",
        "title": "Bioscope — Dev's Podcast",
        "slug": "bioscope-devs-podcast",
        "aspect": "16:9",
        "duration": 127,
        "w": 1280,
        "h": 720,
        "tone": "#676767",
        "discipline": "podcast",
        "kicker": "Long form"
      }
    ]
  },
  {
    "slug": "vlog",
    "title": "Vlog Montage",
    "kicker": "Long form",
    "blurb": "Travel and lifestyle montage cut for retention: strong cold open, momentum through the middle, a landing that earns the last frame.",
    "accent": "#6FD08C",
    "works": [
      {
        "id": "1219777661",
        "title": "Vlog Montage",
        "slug": "vlog-montage",
        "aspect": "16:9",
        "duration": 20,
        "w": 1280,
        "h": 720,
        "tone": "#908363",
        "discipline": "vlog",
        "kicker": "Long form"
      }
    ]
  },
  {
    "slug": "nostalgic",
    "title": "Nostalgic Edits",
    "kicker": "Rhythm",
    "blurb": "Seven quieter edits built on warmth and restraint — grain, gentle halation, typography used as punctuation. Made to feel remembered rather than watched.",
    "accent": "#C08457",
    "works": [
      {
        "id": "1220553072",
        "title": "Riverfront Storyline",
        "slug": "riverfront-storyline",
        "aspect": "16:9",
        "duration": 21,
        "w": 1280,
        "h": 720,
        "tone": "#2b210f",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1219776317",
        "title": "Love Me Not",
        "slug": "love-me-not",
        "aspect": "16:9",
        "duration": 34,
        "w": 1280,
        "h": 720,
        "tone": "#6681f2",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1220552662",
        "title": "Uttarayan",
        "slug": "uttarayan",
        "aspect": "16:9",
        "duration": 14,
        "w": 1280,
        "h": 720,
        "tone": "#793506",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1220557262",
        "title": "Typography Study",
        "slug": "typography-study",
        "aspect": "16:9",
        "duration": 9,
        "w": 1280,
        "h": 721,
        "tone": "#837a5f",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1220553768",
        "title": "Mumbai Montage",
        "slug": "mumbai-montage",
        "aspect": "16:9",
        "duration": 12,
        "w": 1280,
        "h": 720,
        "tone": "#1c1f13",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1220548697",
        "title": "Chalo Chale",
        "slug": "chalo-chale",
        "aspect": "16:9",
        "duration": 26,
        "w": 1280,
        "h": 720,
        "tone": "#171412",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      },
      {
        "id": "1219766021",
        "title": "City on Fire",
        "slug": "city-on-fire",
        "aspect": "16:9",
        "duration": 34,
        "w": 1280,
        "h": 722,
        "tone": "#6e5950",
        "discipline": "nostalgic",
        "kicker": "Rhythm"
      }
    ]
  },
  {
    "slug": "anime-grade",
    "title": "Anime Colour Grading",
    "kicker": "Study",
    "blurb": "Grading animation is a different problem to grading footage — flat cel colour, hard line art, no film response to lean on. These rebuild depth and atmosphere into already-finished frames.",
    "accent": "#3D6681",
    "works": [
      {
        "id": "1219779416",
        "title": "Tengen — Edgy",
        "slug": "tengen-edgy",
        "aspect": "16:9",
        "duration": 10,
        "w": 1280,
        "h": 719,
        "tone": "#ea4227",
        "discipline": "anime-grade",
        "kicker": "Study"
      },
      {
        "id": "1219778853",
        "title": "Tengen — Shake",
        "slug": "tengen-shake",
        "aspect": "16:9",
        "duration": 13,
        "w": 1280,
        "h": 719,
        "tone": "#223046",
        "discipline": "anime-grade",
        "kicker": "Study"
      },
      {
        "id": "1219779517",
        "title": "Douma",
        "slug": "douma",
        "aspect": "16:9",
        "duration": 15,
        "w": 1280,
        "h": 719,
        "tone": "#c7844e",
        "discipline": "anime-grade",
        "kicker": "Study"
      }
    ]
  },
  {
    "slug": "anime-fast",
    "title": "Fast-Paced Anime",
    "kicker": "Study",
    "blurb": "High-intensity anime edits: rotation and shake rigs, impact frames, transitions timed to the frame. Technical exercises in how hard a cut can hit.",
    "accent": "#FF9E3D",
    "works": [
      {
        "id": "1220745541",
        "title": "Giyu — Edgy Rotation",
        "slug": "giyu-edgy-rotation",
        "aspect": "16:9",
        "duration": 10,
        "w": 1280,
        "h": 720,
        "tone": "#32575c",
        "discipline": "anime-fast",
        "kicker": "Study"
      },
      {
        "id": "1220411975",
        "title": "Naruto",
        "slug": "naruto",
        "aspect": "16:9",
        "duration": 28,
        "w": 1280,
        "h": 720,
        "tone": "#8f8a7f",
        "discipline": "anime-fast",
        "kicker": "Study"
      },
      {
        "id": "1220411973",
        "title": "Havana GFX",
        "slug": "havana-gfx",
        "aspect": "16:9",
        "duration": 18,
        "w": 1280,
        "h": 720,
        "tone": "#254243",
        "discipline": "anime-fast",
        "kicker": "Study"
      },
      {
        "id": "1220411974",
        "title": "Demon Slayer",
        "slug": "demon-slayer",
        "aspect": "16:9",
        "duration": 46,
        "w": 1280,
        "h": 720,
        "tone": "#010501",
        "discipline": "anime-fast",
        "kicker": "Study"
      }
    ]
  },
  {
    "slug": "personal",
    "title": "Personal Edits",
    "kicker": "Study",
    "blurb": "Edits made for no client and no brief — where the transitions and grades that later end up in commercial work get tried out first.",
    "accent": "#B9966E",
    "works": [
      {
        "id": "1219758000",
        "title": "Drunk & Nasty",
        "slug": "drunk-and-nasty",
        "aspect": "3:4",
        "duration": 10,
        "w": 1280,
        "h": 1707,
        "tone": "#252423",
        "discipline": "personal",
        "kicker": "Study"
      },
      {
        "id": "1220554545",
        "title": "Concert — Personal Cut",
        "slug": "concert-personal-cut",
        "aspect": "3:4",
        "duration": 16,
        "w": 1280,
        "h": 1707,
        "tone": "#a275b6",
        "discipline": "personal",
        "kicker": "Study"
      }
    ]
  }
];

export const SKILLS: Skill[] = [
  {
    "name": "Colour Grading",
    "desc": "The reason most edits either feel cinematic or feel flat. Primary balance, secondary isolation, split-toned shadows and highlight roll-off — building a look that carries the mood of the story instead of sitting on a LUT."
  },
  {
    "name": "After Effects — VFX & Compositing",
    "desc": "Where the hard problems get solved. Multi-layer compositing, clean-up, screen replacement, light wrap and integration work that makes added elements read as though they were shot in camera."
  },
  {
    "name": "Video Rescue",
    "desc": "Underexposed, noisy, wrongly white-balanced, shot on the wrong settings — I can take footage a client has written off and pull a usable, good-looking cut out of it. Denoise, recover, regrade, stabilise, resharpen."
  },
  {
    "name": "Masking & Rotoscoping",
    "desc": "Frame-by-frame subject isolation. Type that passes behind a moving person, objects removed from a plate, selective grades that follow a face through a shot."
  },
  {
    "name": "Motion Tracking",
    "desc": "2D and camera tracking to pin graphics, text and replacements into moving footage so they hold their place through handheld, whip pans and speed ramps."
  },
  {
    "name": "Logo & Brand Animation",
    "desc": "Identity in motion — logo builds, stingers and end cards with easing and weight that match how the brand is supposed to feel."
  },
  {
    "name": "Kinetic Typography",
    "desc": "Type treated as a performer. Layout, timing and velocity worked so the words land on the beat and carry meaning rather than just filling frame."
  },
  {
    "name": "Cinematography",
    "desc": "Full working knowledge of the camera — exposure triangle, shutter angle, picture profiles, log capture, lens choice and movement. I can shoot the footage I'd want to be handed as an editor."
  },
  {
    "name": "Lighting",
    "desc": "Shaping with key, fill and separation, colour temperature control and practical sources — so the grade starts from something worth grading."
  },
  {
    "name": "Premiere Pro",
    "desc": "The assembly room. Multi-cam sync, proxy workflows, nested sequence structures and delivery-ready exports for every platform spec."
  },
  {
    "name": "CapCut Advance",
    "desc": "Pushed well past template territory. Used deliberately for speed on short-form turnarounds where a same-day deliverable matters more than a round trip."
  },
  {
    "name": "Live Stream Banner Animation",
    "desc": "Looping overlays, animated lower thirds, scoreboards and transition stingers built to run live without dropping frames."
  },
  {
    "name": "Sound Engineering",
    "desc": "Dialogue cleanup, levelling and de-noising, music bedding, ducking and sound design hits. Half of how 'cinematic' an edit feels is what you're hearing."
  },
  {
    "name": "Creative Direction",
    "desc": "Turning a loose brief into a treatment — reference, structure, pacing and look decided before the timeline opens."
  },
  {
    "name": "Content Creation",
    "desc": "Understanding the platform as well as the craft: hooks, retention curves, aspect ratios and what actually makes someone stop scrolling."
  }
];

export const SERVICES: Service[] = [
  {
    "name": "Cinematic Colour Grading",
    "desc": "Mood-driven grading that gives footage a premium, film-like look. Shot matching across cameras, skin tones protected, a bespoke look built per project — not a preset dropped on a timeline."
  },
  {
    "name": "Motion Graphics & Typography",
    "desc": "Text animation, title systems and animated graphics that make content stand out and hold a viewer's eye exactly where you need it."
  },
  {
    "name": "Reels & Short-Form",
    "desc": "Fast-paced, trend-driven vertical edits built for reach — engineered around the hook, the beat and the loop."
  },
  {
    "name": "Long-Form & After-Movies",
    "desc": "YouTube episodes, event after-movies and documentary-style cuts structured for retention from cold open to end card."
  },
  {
    "name": "High-Impact Action Edits",
    "desc": "Heavy-editing builds — speed ramps, impact frames, camera shake rigs, compositing and effects work for edits that need to hit hard."
  },
  {
    "name": "Trending Effects & Transitions",
    "desc": "Viral editing styles and transitions applied with judgement, to lift engagement without making the work look disposable."
  }
];

export const STATS: PortfolioStats = {
  "edits": 52,
  "categories": 16
};

export const UNIQUE_WORKS: Work[] = [
  {
    "id": "1220554546",
    "title": "Mumbai",
    "slug": "mumbai",
    "aspect": "16:9",
    "duration": 30,
    "w": 1280,
    "h": 720,
    "tone": "#66584c",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220555808",
    "title": "Jackie Chan — Cinematic",
    "slug": "jackie-chan-cinematic",
    "aspect": "4:3",
    "duration": 16,
    "w": 1280,
    "h": 960,
    "tone": "#22281b",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220555284",
    "title": "She's Running Out the Door",
    "slug": "shes-running-out-the-door",
    "aspect": "16:9",
    "duration": 37,
    "w": 1280,
    "h": 725,
    "tone": "#6f6050",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220556151",
    "title": "Conroy — Cinematic Reel",
    "slug": "conroy-cinematic-reel",
    "aspect": "16:9",
    "duration": 22,
    "w": 1280,
    "h": 720,
    "tone": "#564b41",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1219763361",
    "title": "Ankit Tiwari — Live at Nirma",
    "slug": "ankit-tiwari-live-at-nirma",
    "aspect": "16:9",
    "duration": 42,
    "w": 1280,
    "h": 720,
    "tone": "#1d110d",
    "discipline": "concert-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219757810",
    "title": "LJ — Masked Edit",
    "slug": "lj-masked-edit",
    "aspect": "4:3",
    "duration": 20,
    "w": 1280,
    "h": 960,
    "tone": "#23201b",
    "discipline": "masking",
    "kicker": "Craft"
  },
  {
    "id": "1219763331",
    "title": "Stranger Things",
    "slug": "stranger-things",
    "aspect": "16:9",
    "duration": 47,
    "w": 1280,
    "h": 720,
    "tone": "#b11a09",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1219763230",
    "title": "LJ — Velocity / Poster Boy",
    "slug": "lj-velocity-poster-boy",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#9f8874",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1219758725",
    "title": "House of Hobos",
    "slug": "house-of-hobos",
    "aspect": "9:16",
    "duration": 12,
    "w": 1280,
    "h": 2276,
    "tone": "#24170a",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1220413186",
    "title": "Rock Your Body",
    "slug": "rock-your-body",
    "aspect": "16:9",
    "duration": 24,
    "w": 1280,
    "h": 720,
    "tone": "#b76f62",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220553507",
    "title": "Ruthless — LJ",
    "slug": "ruthless-lj",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#54392e",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220548695",
    "title": "Riverfront Montage",
    "slug": "riverfront-montage",
    "aspect": "16:9",
    "duration": 14,
    "w": 1280,
    "h": 721,
    "tone": "#72100b",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220554808",
    "title": "Ahmedabad BRTS",
    "slug": "ahmedabad-brts",
    "aspect": "16:9",
    "duration": 24,
    "w": 1280,
    "h": 720,
    "tone": "#fc5519",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220559375",
    "title": "Abhivyakti",
    "slug": "abhivyakti",
    "aspect": "16:9",
    "duration": 20,
    "w": 1280,
    "h": 720,
    "tone": "#453117",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220557252",
    "title": "Radiohead",
    "slug": "radiohead",
    "aspect": "16:9",
    "duration": 36,
    "w": 1280,
    "h": 719,
    "tone": "#892737",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220559007",
    "title": "Auditorium Jamming",
    "slug": "auditorium-jamming",
    "aspect": "16:9",
    "duration": 81,
    "w": 1280,
    "h": 720,
    "tone": "#210808",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220552857",
    "title": "Conroy — Reel 01",
    "slug": "conroy-reel-01",
    "aspect": "9:16",
    "duration": 22,
    "w": 1280,
    "h": 2276,
    "tone": "#6e5b55",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550982",
    "title": "Conroy — Reel 02",
    "slug": "conroy-reel-02",
    "aspect": "9:16",
    "duration": 19,
    "w": 1280,
    "h": 2276,
    "tone": "#664f48",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550831",
    "title": "Conroy — Reel 03",
    "slug": "conroy-reel-03",
    "aspect": "9:16",
    "duration": 17,
    "w": 1280,
    "h": 2276,
    "tone": "#dfd3d1",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550347",
    "title": "Conroy — Reel 04",
    "slug": "conroy-reel-04",
    "aspect": "9:16",
    "duration": 34,
    "w": 1280,
    "h": 2276,
    "tone": "#d4caae",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549555",
    "title": "Conroy — Reel 05",
    "slug": "conroy-reel-05",
    "aspect": "9:16",
    "duration": 24,
    "w": 1280,
    "h": 2276,
    "tone": "#8b6e66",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549430",
    "title": "Conroy — Reel 06",
    "slug": "conroy-reel-06",
    "aspect": "9:16",
    "duration": 14,
    "w": 1280,
    "h": 2276,
    "tone": "#cac6c7",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549151",
    "title": "Conroy — Reel 07",
    "slug": "conroy-reel-07",
    "aspect": "9:16",
    "duration": 19,
    "w": 1280,
    "h": 2276,
    "tone": "#73614b",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220548698",
    "title": "Conroy — Reel 08",
    "slug": "conroy-reel-08",
    "aspect": "9:16",
    "duration": 20,
    "w": 1280,
    "h": 2276,
    "tone": "#d0baac",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220548696",
    "title": "Conroy — Reel 09",
    "slug": "conroy-reel-09",
    "aspect": "9:16",
    "duration": 12,
    "w": 1280,
    "h": 2276,
    "tone": "#3c4a4c",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1219767934",
    "title": "Halaji Tara Hath Vakhanu — Rushabh Ahir Live",
    "slug": "halaji-tara-hath-vakhanu-rushabh-ahir-live",
    "aspect": "16:9",
    "duration": 47,
    "w": 1280,
    "h": 720,
    "tone": "#1b1910",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219766019",
    "title": "Nirma Activity Reel",
    "slug": "nirma-activity-reel",
    "aspect": "16:9",
    "duration": 32,
    "w": 1280,
    "h": 720,
    "tone": "#241c1d",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219758002",
    "title": "Hackathon — The Full Film",
    "slug": "hackathon-the-full-film",
    "aspect": "16:9",
    "duration": 128,
    "w": 1280,
    "h": 720,
    "tone": "#5b7075",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556772",
    "title": "Rushabh Ahir — Vertical Cut",
    "slug": "rushabh-ahir-vertical-cut",
    "aspect": "9:16",
    "duration": 42,
    "w": 1280,
    "h": 2276,
    "tone": "#4b3a30",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556182",
    "title": "Pyaar Kya Hai",
    "slug": "pyaar-kya-hai",
    "aspect": "9:16",
    "duration": 38,
    "w": 1280,
    "h": 2276,
    "tone": "#c8866b",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556261",
    "title": "Tech Café",
    "slug": "tech-cafe",
    "aspect": "9:16",
    "duration": 24,
    "w": 1280,
    "h": 2276,
    "tone": "#938571",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219757999",
    "title": "Hackathon — Title Sequence",
    "slug": "hackathon-title-sequence",
    "aspect": "16:9",
    "duration": 7,
    "w": 1280,
    "h": 720,
    "tone": "#01003d",
    "discipline": "event-gfx",
    "kicker": "Craft"
  },
  {
    "id": "1219760653",
    "title": "Card — 3D Visual",
    "slug": "card-3d-visual",
    "aspect": "9:16",
    "duration": 13,
    "w": 1280,
    "h": 2276,
    "tone": "#6e4e62",
    "discipline": "3d-visualization",
    "kicker": "Craft"
  },
  {
    "id": "1220413187",
    "title": "Enola Holmes",
    "slug": "enola-holmes",
    "aspect": "4:3",
    "duration": 24,
    "w": 1280,
    "h": 961,
    "tone": "#1d1514",
    "discipline": "smooth-movie",
    "kicker": "Rhythm"
  },
  {
    "id": "1219766024",
    "title": "Bioscope — Dev's Podcast",
    "slug": "bioscope-devs-podcast",
    "aspect": "16:9",
    "duration": 127,
    "w": 1280,
    "h": 720,
    "tone": "#676767",
    "discipline": "podcast",
    "kicker": "Long form"
  },
  {
    "id": "1219777661",
    "title": "Vlog Montage",
    "slug": "vlog-montage",
    "aspect": "16:9",
    "duration": 20,
    "w": 1280,
    "h": 720,
    "tone": "#908363",
    "discipline": "vlog",
    "kicker": "Long form"
  },
  {
    "id": "1220553072",
    "title": "Riverfront Storyline",
    "slug": "riverfront-storyline",
    "aspect": "16:9",
    "duration": 21,
    "w": 1280,
    "h": 720,
    "tone": "#2b210f",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219776317",
    "title": "Love Me Not",
    "slug": "love-me-not",
    "aspect": "16:9",
    "duration": 34,
    "w": 1280,
    "h": 720,
    "tone": "#6681f2",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220552662",
    "title": "Uttarayan",
    "slug": "uttarayan",
    "aspect": "16:9",
    "duration": 14,
    "w": 1280,
    "h": 720,
    "tone": "#793506",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220557262",
    "title": "Typography Study",
    "slug": "typography-study",
    "aspect": "16:9",
    "duration": 9,
    "w": 1280,
    "h": 721,
    "tone": "#837a5f",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220553768",
    "title": "Mumbai Montage",
    "slug": "mumbai-montage",
    "aspect": "16:9",
    "duration": 12,
    "w": 1280,
    "h": 720,
    "tone": "#1c1f13",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220548697",
    "title": "Chalo Chale",
    "slug": "chalo-chale",
    "aspect": "16:9",
    "duration": 26,
    "w": 1280,
    "h": 720,
    "tone": "#171412",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219766021",
    "title": "City on Fire",
    "slug": "city-on-fire",
    "aspect": "16:9",
    "duration": 34,
    "w": 1280,
    "h": 722,
    "tone": "#6e5950",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219779416",
    "title": "Tengen — Edgy",
    "slug": "tengen-edgy",
    "aspect": "16:9",
    "duration": 10,
    "w": 1280,
    "h": 719,
    "tone": "#ea4227",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1219778853",
    "title": "Tengen — Shake",
    "slug": "tengen-shake",
    "aspect": "16:9",
    "duration": 13,
    "w": 1280,
    "h": 719,
    "tone": "#223046",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1219779517",
    "title": "Douma",
    "slug": "douma",
    "aspect": "16:9",
    "duration": 15,
    "w": 1280,
    "h": 719,
    "tone": "#c7844e",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1220745541",
    "title": "Giyu — Edgy Rotation",
    "slug": "giyu-edgy-rotation",
    "aspect": "16:9",
    "duration": 10,
    "w": 1280,
    "h": 720,
    "tone": "#32575c",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411975",
    "title": "Naruto",
    "slug": "naruto",
    "aspect": "16:9",
    "duration": 28,
    "w": 1280,
    "h": 720,
    "tone": "#8f8a7f",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411973",
    "title": "Havana GFX",
    "slug": "havana-gfx",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#254243",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411974",
    "title": "Demon Slayer",
    "slug": "demon-slayer",
    "aspect": "16:9",
    "duration": 46,
    "w": 1280,
    "h": 720,
    "tone": "#010501",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1219758000",
    "title": "Drunk & Nasty",
    "slug": "drunk-and-nasty",
    "aspect": "3:4",
    "duration": 10,
    "w": 1280,
    "h": 1707,
    "tone": "#252423",
    "discipline": "personal",
    "kicker": "Study"
  },
  {
    "id": "1220554545",
    "title": "Concert — Personal Cut",
    "slug": "concert-personal-cut",
    "aspect": "3:4",
    "duration": 16,
    "w": 1280,
    "h": 1707,
    "tone": "#a275b6",
    "discipline": "personal",
    "kicker": "Study"
  }
];

export const ALL_WORKS: Work[] = [
  {
    "id": "1220554546",
    "title": "Mumbai",
    "slug": "mumbai",
    "aspect": "16:9",
    "duration": 30,
    "w": 1280,
    "h": 720,
    "tone": "#66584c",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220555808",
    "title": "Jackie Chan — Cinematic",
    "slug": "jackie-chan-cinematic",
    "aspect": "4:3",
    "duration": 16,
    "w": 1280,
    "h": 960,
    "tone": "#22281b",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220555284",
    "title": "She's Running Out the Door",
    "slug": "shes-running-out-the-door",
    "aspect": "16:9",
    "duration": 37,
    "w": 1280,
    "h": 725,
    "tone": "#6f6050",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1220556151",
    "title": "Conroy — Cinematic Reel",
    "slug": "conroy-cinematic-reel",
    "aspect": "16:9",
    "duration": 22,
    "w": 1280,
    "h": 720,
    "tone": "#564b41",
    "discipline": "absolute-cinema",
    "kicker": "Craft"
  },
  {
    "id": "1219763361",
    "title": "Ankit Tiwari — Live at Nirma",
    "slug": "ankit-tiwari-live-at-nirma",
    "aspect": "16:9",
    "duration": 42,
    "w": 1280,
    "h": 720,
    "tone": "#1d110d",
    "discipline": "concert-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219757810",
    "title": "LJ — Masked Edit",
    "slug": "lj-masked-edit",
    "aspect": "4:3",
    "duration": 20,
    "w": 1280,
    "h": 960,
    "tone": "#23201b",
    "discipline": "masking",
    "kicker": "Craft"
  },
  {
    "id": "1219763331",
    "title": "Stranger Things",
    "slug": "stranger-things",
    "aspect": "16:9",
    "duration": 47,
    "w": 1280,
    "h": 720,
    "tone": "#b11a09",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1219763230",
    "title": "LJ — Velocity / Poster Boy",
    "slug": "lj-velocity-poster-boy",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#9f8874",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1219758725",
    "title": "House of Hobos",
    "slug": "house-of-hobos",
    "aspect": "9:16",
    "duration": 12,
    "w": 1280,
    "h": 2276,
    "tone": "#24170a",
    "discipline": "motion-graphics",
    "kicker": "Craft"
  },
  {
    "id": "1220413186",
    "title": "Rock Your Body",
    "slug": "rock-your-body",
    "aspect": "16:9",
    "duration": 24,
    "w": 1280,
    "h": 720,
    "tone": "#b76f62",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220553507",
    "title": "Ruthless — LJ",
    "slug": "ruthless-lj",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#54392e",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220548695",
    "title": "Riverfront Montage",
    "slug": "riverfront-montage",
    "aspect": "16:9",
    "duration": 14,
    "w": 1280,
    "h": 721,
    "tone": "#72100b",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220554808",
    "title": "Ahmedabad BRTS",
    "slug": "ahmedabad-brts",
    "aspect": "16:9",
    "duration": 24,
    "w": 1280,
    "h": 720,
    "tone": "#fc5519",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220559375",
    "title": "Abhivyakti",
    "slug": "abhivyakti",
    "aspect": "16:9",
    "duration": 20,
    "w": 1280,
    "h": 720,
    "tone": "#453117",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220557252",
    "title": "Radiohead",
    "slug": "radiohead",
    "aspect": "16:9",
    "duration": 36,
    "w": 1280,
    "h": 719,
    "tone": "#892737",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220559007",
    "title": "Auditorium Jamming",
    "slug": "auditorium-jamming",
    "aspect": "16:9",
    "duration": 81,
    "w": 1280,
    "h": 720,
    "tone": "#210808",
    "discipline": "fast-montage",
    "kicker": "Rhythm"
  },
  {
    "id": "1220556151",
    "title": "Conroy — Cinematic Reel",
    "slug": "conroy-cinematic-reel",
    "aspect": "16:9",
    "duration": 22,
    "w": 1280,
    "h": 720,
    "tone": "#564b41",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220552857",
    "title": "Conroy — Reel 01",
    "slug": "conroy-reel-01",
    "aspect": "9:16",
    "duration": 22,
    "w": 1280,
    "h": 2276,
    "tone": "#6e5b55",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550982",
    "title": "Conroy — Reel 02",
    "slug": "conroy-reel-02",
    "aspect": "9:16",
    "duration": 19,
    "w": 1280,
    "h": 2276,
    "tone": "#664f48",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550831",
    "title": "Conroy — Reel 03",
    "slug": "conroy-reel-03",
    "aspect": "9:16",
    "duration": 17,
    "w": 1280,
    "h": 2276,
    "tone": "#dfd3d1",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220550347",
    "title": "Conroy — Reel 04",
    "slug": "conroy-reel-04",
    "aspect": "9:16",
    "duration": 34,
    "w": 1280,
    "h": 2276,
    "tone": "#d4caae",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549555",
    "title": "Conroy — Reel 05",
    "slug": "conroy-reel-05",
    "aspect": "9:16",
    "duration": 24,
    "w": 1280,
    "h": 2276,
    "tone": "#8b6e66",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549430",
    "title": "Conroy — Reel 06",
    "slug": "conroy-reel-06",
    "aspect": "9:16",
    "duration": 14,
    "w": 1280,
    "h": 2276,
    "tone": "#cac6c7",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220549151",
    "title": "Conroy — Reel 07",
    "slug": "conroy-reel-07",
    "aspect": "9:16",
    "duration": 19,
    "w": 1280,
    "h": 2276,
    "tone": "#73614b",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220548698",
    "title": "Conroy — Reel 08",
    "slug": "conroy-reel-08",
    "aspect": "9:16",
    "duration": 20,
    "w": 1280,
    "h": 2276,
    "tone": "#d0baac",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1220548696",
    "title": "Conroy — Reel 09",
    "slug": "conroy-reel-09",
    "aspect": "9:16",
    "duration": 12,
    "w": 1280,
    "h": 2276,
    "tone": "#3c4a4c",
    "discipline": "brand-films",
    "kicker": "Client work"
  },
  {
    "id": "1219767934",
    "title": "Halaji Tara Hath Vakhanu — Rushabh Ahir Live",
    "slug": "halaji-tara-hath-vakhanu-rushabh-ahir-live",
    "aspect": "16:9",
    "duration": 47,
    "w": 1280,
    "h": 720,
    "tone": "#1b1910",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219766019",
    "title": "Nirma Activity Reel",
    "slug": "nirma-activity-reel",
    "aspect": "16:9",
    "duration": 32,
    "w": 1280,
    "h": 720,
    "tone": "#241c1d",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219758002",
    "title": "Hackathon — The Full Film",
    "slug": "hackathon-the-full-film",
    "aspect": "16:9",
    "duration": 128,
    "w": 1280,
    "h": 720,
    "tone": "#5b7075",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556772",
    "title": "Rushabh Ahir — Vertical Cut",
    "slug": "rushabh-ahir-vertical-cut",
    "aspect": "9:16",
    "duration": 42,
    "w": 1280,
    "h": 2276,
    "tone": "#4b3a30",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556182",
    "title": "Pyaar Kya Hai",
    "slug": "pyaar-kya-hai",
    "aspect": "9:16",
    "duration": 38,
    "w": 1280,
    "h": 2276,
    "tone": "#c8866b",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1220556261",
    "title": "Tech Café",
    "slug": "tech-cafe",
    "aspect": "9:16",
    "duration": 24,
    "w": 1280,
    "h": 2276,
    "tone": "#938571",
    "discipline": "event-edits",
    "kicker": "Client work"
  },
  {
    "id": "1219757999",
    "title": "Hackathon — Title Sequence",
    "slug": "hackathon-title-sequence",
    "aspect": "16:9",
    "duration": 7,
    "w": 1280,
    "h": 720,
    "tone": "#01003d",
    "discipline": "event-gfx",
    "kicker": "Craft"
  },
  {
    "id": "1219760653",
    "title": "Card — 3D Visual",
    "slug": "card-3d-visual",
    "aspect": "9:16",
    "duration": 13,
    "w": 1280,
    "h": 2276,
    "tone": "#6e4e62",
    "discipline": "3d-visualization",
    "kicker": "Craft"
  },
  {
    "id": "1220413187",
    "title": "Enola Holmes",
    "slug": "enola-holmes",
    "aspect": "4:3",
    "duration": 24,
    "w": 1280,
    "h": 961,
    "tone": "#1d1514",
    "discipline": "smooth-movie",
    "kicker": "Rhythm"
  },
  {
    "id": "1219766024",
    "title": "Bioscope — Dev's Podcast",
    "slug": "bioscope-devs-podcast",
    "aspect": "16:9",
    "duration": 127,
    "w": 1280,
    "h": 720,
    "tone": "#676767",
    "discipline": "podcast",
    "kicker": "Long form"
  },
  {
    "id": "1219777661",
    "title": "Vlog Montage",
    "slug": "vlog-montage",
    "aspect": "16:9",
    "duration": 20,
    "w": 1280,
    "h": 720,
    "tone": "#908363",
    "discipline": "vlog",
    "kicker": "Long form"
  },
  {
    "id": "1220553072",
    "title": "Riverfront Storyline",
    "slug": "riverfront-storyline",
    "aspect": "16:9",
    "duration": 21,
    "w": 1280,
    "h": 720,
    "tone": "#2b210f",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219776317",
    "title": "Love Me Not",
    "slug": "love-me-not",
    "aspect": "16:9",
    "duration": 34,
    "w": 1280,
    "h": 720,
    "tone": "#6681f2",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220552662",
    "title": "Uttarayan",
    "slug": "uttarayan",
    "aspect": "16:9",
    "duration": 14,
    "w": 1280,
    "h": 720,
    "tone": "#793506",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220557262",
    "title": "Typography Study",
    "slug": "typography-study",
    "aspect": "16:9",
    "duration": 9,
    "w": 1280,
    "h": 721,
    "tone": "#837a5f",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220553768",
    "title": "Mumbai Montage",
    "slug": "mumbai-montage",
    "aspect": "16:9",
    "duration": 12,
    "w": 1280,
    "h": 720,
    "tone": "#1c1f13",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1220548697",
    "title": "Chalo Chale",
    "slug": "chalo-chale",
    "aspect": "16:9",
    "duration": 26,
    "w": 1280,
    "h": 720,
    "tone": "#171412",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219766021",
    "title": "City on Fire",
    "slug": "city-on-fire",
    "aspect": "16:9",
    "duration": 34,
    "w": 1280,
    "h": 722,
    "tone": "#6e5950",
    "discipline": "nostalgic",
    "kicker": "Rhythm"
  },
  {
    "id": "1219779416",
    "title": "Tengen — Edgy",
    "slug": "tengen-edgy",
    "aspect": "16:9",
    "duration": 10,
    "w": 1280,
    "h": 719,
    "tone": "#ea4227",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1219778853",
    "title": "Tengen — Shake",
    "slug": "tengen-shake",
    "aspect": "16:9",
    "duration": 13,
    "w": 1280,
    "h": 719,
    "tone": "#223046",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1219779517",
    "title": "Douma",
    "slug": "douma",
    "aspect": "16:9",
    "duration": 15,
    "w": 1280,
    "h": 719,
    "tone": "#c7844e",
    "discipline": "anime-grade",
    "kicker": "Study"
  },
  {
    "id": "1220745541",
    "title": "Giyu — Edgy Rotation",
    "slug": "giyu-edgy-rotation",
    "aspect": "16:9",
    "duration": 10,
    "w": 1280,
    "h": 720,
    "tone": "#32575c",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411975",
    "title": "Naruto",
    "slug": "naruto",
    "aspect": "16:9",
    "duration": 28,
    "w": 1280,
    "h": 720,
    "tone": "#8f8a7f",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411973",
    "title": "Havana GFX",
    "slug": "havana-gfx",
    "aspect": "16:9",
    "duration": 18,
    "w": 1280,
    "h": 720,
    "tone": "#254243",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1220411974",
    "title": "Demon Slayer",
    "slug": "demon-slayer",
    "aspect": "16:9",
    "duration": 46,
    "w": 1280,
    "h": 720,
    "tone": "#010501",
    "discipline": "anime-fast",
    "kicker": "Study"
  },
  {
    "id": "1219758000",
    "title": "Drunk & Nasty",
    "slug": "drunk-and-nasty",
    "aspect": "3:4",
    "duration": 10,
    "w": 1280,
    "h": 1707,
    "tone": "#252423",
    "discipline": "personal",
    "kicker": "Study"
  },
  {
    "id": "1220554545",
    "title": "Concert — Personal Cut",
    "slug": "concert-personal-cut",
    "aspect": "3:4",
    "duration": 16,
    "w": 1280,
    "h": 1707,
    "tone": "#a275b6",
    "discipline": "personal",
    "kicker": "Study"
  }
];

export const WORKS_BY_SLUG: Record<string, Work> = Object.fromEntries(
  UNIQUE_WORKS.map(w => [w.slug, w])
);

export const WORKS_BY_ID: Record<string, Work> = Object.fromEntries(
  UNIQUE_WORKS.map(w => [w.id, w])
);
